---
version: '3'
services:
  pi_associates:
    image: pi_associates:syduc
    container_name: pi_associates_syduc
    volumes:
      - "./pi_associates:/app"
      - "./data:/data"
    stdin_open: true
    tty: true
    environment:
      PI_ASSOCIATES_KISVN_LOG_DIR: '/data/kisvn/log'
      PI_ASSOCIATES_KISVN_TICKDATA_DIR_RAW: '/data/kisvn/raw_data'
      PI_ASSOCIATES_KISVN_TICKDATA_DIR_PROCESSED: '/data/kisvn/processed_data'
      PI_ASSOCIATES_VN30_EXTENSION_SYMBOLS: 'ACB,BID,BVH,CTG,FPT,GAS,GVR,HDB,HPG,KDH,MBB,MSN,MWG,NVL,PDR,PLX,PNJ,POW,SAB,SSI,STB,TCB,TPB,VCB,VHM,VIC,VJC,VNM,VPB,VRE,BCM,VIB,VN30'
      PI_ASSOCIATES_VN30INDEX_SYMBOL: 'VN30'
      PI_ASSOCIATES_VN30_SYMBOLS: 'ACB,BCM,BID,BVH,CTG,FPT,GAS,GVR,HDB,HPG,MBB,MSN,MWG,NVL,PDR,PLX,POW,SAB,SSI,STB,TCB,TPB,VCB,VHM,VIB,VIC,VJC,VNM,VPB,VRE'
