---
version: '3'
services:
  pi_associates:
    image: pi_associates:syduc
    container_name: pi_associates_syduc
    volumes:
      - "./pi_associates:/app"
      - "./data:/data"
    stdin_open: true
    tty: true
    environment:
      PI_ASSOCIATES_KISVN_LOG_DATA_DIRPATH: '/data/kisvn/log_data'
      PI_ASSOCIATES_KISVN_RAW_DATA_DIRPATH: '/data/kisvn/raw_data'
      PI_ASSOCIATES_KISVN_PROCESSED_DATA_DIRPATH: '/data/kisvn/processed_data'
      PI_ASSOCIATES_VPS_LOG_DATA_DIRPATH: '/data/vps/log_data'
      PI_ASSOCIATES_VNINDEX_SYMBOLS: 'VN30,ACB,BID,BVH,CTG,FPT,GAS,GVR,HDB,HPG,KDH,MBB,MSN,MWG,NVL,PDR,PLX,PNJ,POW,SAB,SSI,STB,TCB,TPB,VCB,VHM,VIC,VJC,VNM,VPB,VRE'
      PI_ASSOCIATES_VN30_SYMBOLS: 'ACB,BID,BVH,CTG,FPT,GAS,GVR,HDB,HPG,KDH,MBB,MSN,MWG,NVL,PDR,PLX,PNJ,POW,SAB,SSI,STB,TCB,TPB,VCB,VHM,VIC,VJC,VNM,VPB,VRE'
      PI_ASSOCIATES_BINANCE_SCRAPED_SYMBOLS: 'btcusdt,ethusd'
